### ISSUE TITLE
Crickey! message

### ISSUE THREAD

**Issue by 1spb-org** [OrthoCube/grav-plugin-tag-manager#1]
The Crickey! message appears right after install with current ver. of Grav

**Comment by aricooperdavis** [comment]
It's the [composer autoloader](https://github.com/OrthoCube/grav-plugin-tag-manager/blob/master/tag-manager.php#L44) that causes the issue because the `/vendor` directory isn't shipped with the plugin. This means that, once you've downloaded the plugin (either from here or using the admin plugin), you'll need to navigate to the plugin directory and run composer to install the dependencies.

i.e. `composer install`

**Comment by 1spb-org** [comment]
Thanks!
